apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/CloudScope/helm-values.git
      targetRevision: main
      ref: values
    - repoURL: https://cloudscope.github.io/helm/charts
      targetRevision: 1.0.0
      chart: argocd-self-managed
      helm:
        valueFiles:
        - $values/argocd-self-managed/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:     
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
      
